heartbeat.monitors:
  - type: http
    name: Kibana
    urls: ["http://ELK_SERVER_IP:5601"]
    schedule: '@every 30s'

  - type: icmp
    name: Ping DC
    hosts: ["DC_IP"]
    schedule: '@every 30s'

output.logstash:
  hosts: ["ELK_SERVER_IP:5046"]
  ssl.enabled: false