version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directories: ["/libs/py-common", "/integrations/outbound", "/services/*"]
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directories: ["/services/*"]
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
