# Listen on UDP 5518 (5514 is used by the Logstash syslog pipeline)
module(load="imudp")  # load once
input(type="imudp" port="5518")

# Write events from the Palo Alto firewall to a file read by Filebeat (panw module)
$template PaloAlto, "/var/log/paloalto/paloalto.log"

if ($fromhost-ip == 'PAN_FW_IP') then -?PaloAlto
& stop