# UDP dinle
module(load="imudp")  # Yalnızca bir kez yükleyin
input(type="imudp" port="5514")

# Palo Alto IP'sinden gelen logları dosyaya yaz
$template PaloAlto, "/var/log/paloalto/paloalto.log"

if ($fromhost-ip == 'PAN_FW_IP') then -?PaloAlto
& stop